spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${env.DATABASE_NAME}
    username: ${env.DATABASE_USER}
    password: ${env.DATABSE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true